class KindredError(Exception): ...


class ValidationError(KindredError): ...


class NotFoundError(KindredError): ...


class UnauthorizedError(KindredError): ...


class ConflictError(KindredError): ...


class SignatureError(KindredError): ...
