"""kindred_membership_invite

Revision ID: 136766a95a04
Revises: 7b592562ac56
Create Date: 2026-04-18 09:05:03.362119

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '136766a95a04'
down_revision: str | Sequence[str] | None = '7b592562ac56'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kindreds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('bless_threshold', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_kindreds_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kindreds')),
    sa.UniqueConstraint('slug', name=op.f('uq_kindreds_slug'))
    )
    op.create_table('invites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kindred_id', sa.Uuid(), nullable=False),
    sa.Column('issued_by', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('uses', sa.Integer(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('issuer_sig', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], name=op.f('fk_invites_issued_by_users')),
    sa.ForeignKeyConstraint(['kindred_id'], ['kindreds.id'], name=op.f('fk_invites_kindred_id_kindreds')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invites')),
    sa.UniqueConstraint('token', name=op.f('uq_invites_token'))
    )
    op.create_table('memberships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('kindred_id', sa.Uuid(), nullable=False),
    sa.Column('invite_sig', sa.LargeBinary(), nullable=False),
    sa.Column('accept_sig', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_memberships_agent_id_agents')),
    sa.ForeignKeyConstraint(['kindred_id'], ['kindreds.id'], name=op.f('fk_memberships_kindred_id_kindreds')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships')),
    sa.UniqueConstraint('agent_id', 'kindred_id', name='membership_uq')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('memberships')
    op.drop_table('invites')
    op.drop_table('kindreds')
    # ### end Alembic commands ###
