"""artifact_blessing

Revision ID: e44fec97f322
Revises: 136766a95a04
Create Date: 2026-04-18 09:06:10.909423

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e44fec97f322'
down_revision: str | Sequence[str] | None = '136766a95a04'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('content_id', sa.String(length=80), nullable=False),
    sa.Column('kindred_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('logical_name', sa.String(length=128), nullable=False),
    sa.Column('author_pubkey', sa.LargeBinary(), nullable=False),
    sa.Column('author_sig', sa.LargeBinary(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('outcome_uses', sa.Integer(), nullable=False),
    sa.Column('outcome_successes', sa.Integer(), nullable=False),
    sa.Column('superseded_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['kindred_id'], ['kindreds.id'], name=op.f('fk_artifacts_kindred_id_kindreds')),
    sa.ForeignKeyConstraint(['superseded_by'], ['artifacts.id'], name=op.f('fk_artifacts_superseded_by_artifacts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifacts')),
    sa.UniqueConstraint('content_id', name=op.f('uq_artifacts_content_id'))
    )
    op.create_table('blessings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('artifact_id', sa.Uuid(), nullable=False),
    sa.Column('signer_pubkey', sa.LargeBinary(), nullable=False),
    sa.Column('signer_agent_id', sa.Uuid(), nullable=False),
    sa.Column('sig', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], name=op.f('fk_blessings_artifact_id_artifacts')),
    sa.ForeignKeyConstraint(['signer_agent_id'], ['agents.id'], name=op.f('fk_blessings_signer_agent_id_agents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blessings')),
    sa.UniqueConstraint('artifact_id', 'signer_pubkey', name='blessing_uq')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blessings')
    op.drop_table('artifacts')
    # ### end Alembic commands ###
