"""audit_event

Revision ID: 1a2c34090472
Revises: e44fec97f322
Create Date: 2026-04-18 09:07:26.094359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a2c34090472'
down_revision: Union[str, Sequence[str], None] = 'e44fec97f322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kindred_id', sa.Uuid(), nullable=False),
    sa.Column('agent_pubkey', sa.LargeBinary(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('facilitator_sig', sa.LargeBinary(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['kindred_id'], ['kindreds.id'], name=op.f('fk_audit_log_kindred_id_kindreds')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kindred_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['kindred_id'], ['kindreds.id'], name=op.f('fk_events_kindred_id_kindreds')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
